### ISSUE TITLE
python manage.py makemigrations home, catalog

### ISSUE THREAD

**Issue by Mcsavvy** [longclawshop/longclaw#387]
# ISSUE\_TEMPLATE

* longclaw version:1.0.2
* Django version:3.2.3
* Python version:3.8.8

## Description

I'm trying to make migrations for home and catalog but I keep getting an error.

(store) (base) ➜  alias migrations="python manage.py makemigrations"
(store) (base) ➜  migrations home catalog
Traceback (most recent call last):                                           
  File "/home/mcsavvy/projects-new/soar/store/lib/python3.8/site-packages/django/apps/config.py", line 244, in create                                     
    app_module = import_module(app_name)                                     
  File "/home/mcsavvy/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                          
    return _bootstrap._gcd_import(name[level:], package, level)    
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import            
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked 
ModuleNotFoundError: No module named 'core'                        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):         
  File "manage.py", line 11, in <module>                                     
    execute_from_command_line(sys.argv)                            
  File "/home/mcsavvy/projects-new/soar/store/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()                                                        
  File "/home/mcsavvy/projects-new/soar/store/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute                       
    django.setup()                      
  File "/home/mcsavvy/projects-new/soar/store/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)                                   
  File "/home/mcsavvy/projects-new/soar/store/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate                                  
    app_config = AppConfig.create(entry)                          
  File "/home/mcsavvy/projects-new/soar/store/lib/python3.8/site-packages/django/apps/config.py", line 246, in create                                     
    raise ImproperlyConfigured(                                              
django.core.exceptions.ImproperlyConfigured: Cannot import 'core'. Check that 'longclaw.core.apps.LongclawcoreConfig.name' is correct.

**Comment by chrisbarry** [comment]
Hey, this is the django 3.2 thing...

I haven't got time to fix now (but will in a bit)

https://www.reddit.com/r/djangolearning/comments/mlgjqn/changed_import_structure_in_django_32/

You could just downgrade django or change the app names inside longclaw, if you're comfortable doing that..

I'll do it in a bit if nobody gets there before me,

CB

**Comment by burchesoka** [comment]
Oh! can you make it in requirments.txt?

**Comment by ArthurJahn** [comment]
I'm having the same issue here.
