### ISSUE TITLE
No module named 'wagtail.core'

### ISSUE THREAD

**Issue by Qoyyuum** [longclawshop/longclaw#486]
# ISSUE\_TEMPLATE

* longclaw version: 1.0.2
* Django version: 4.2.1
* Python version: 3.11.3

## Description
First time, trying our longclaw. I followed the setup guide and tried the `makemigrations` and I've encountered this error.

## Steps to reproduce
```shell
pip install longclaw
longclaw start myshop
cd myshop
python manage.py makemigrations catalog home
```

## Expectations
I expected it would successfully make the migrations scripts.

## Actual
Threw an error that it couldn't find wagtail.core. Traceback as follows:

```python
Traceback (most recent call last):
  File "C:\Users\abdul\Documents\sides\myshop\mymuseum\manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\abdul\.virtualenvs\myshop-O324mA9y\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\abdul\.virtualenvs\myshop-O324mA9y\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\abdul\.virtualenvs\myshop-O324mA9y\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\abdul\.virtualenvs\myshop-O324mA9y\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\.virtualenvs\myshop-O324mA9y\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wagtail.core'
```

Here's my pip freeze list:

```
anyascii==0.3.2
asgiref==3.6.0
beautifulsoup4==4.11.2
certifi==2023.5.7
charset-normalizer==3.1.0
defusedxml==0.7.1
Django==4.2.1
django-countries==7.5.1
django-extensions==3.2.1
django-filter==22.1
django-ipware==5.0.0
django-modelcluster==6.0
django-permissionedforms==0.1
django-taggit==3.1.0
django-treebeard==4.7
djangorestframework==3.14.0
draftjs-exporter==2.1.7
et-xmlfile==1.1.0
filetype==1.2.0
html5lib==1.1
idna==3.4
l18n==2021.3
longclaw==1.0.2
openpyxl==3.1.2
Pillow==9.5.0
pytz==2023.3
requests==2.30.0
six==1.16.0
soupsieve==2.4.1
sqlparse==0.4.4
telepath==0.3
typing_extensions==4.5.0
tzdata==2023.3
urllib3==2.0.2
wagtail==5.0
webencodings==0.5.1
Willow==1.5
```

**Comment by DarkArtek** [comment]
Wagtail has changed some paths. The wagtail version you are Udine it's too new. We will update the code for supporting the new paths.

**Comment by j2l** [comment]
Hello,
I tried today and stumbled on the same issue with wagtail==5.2.2
Is code updated?

**Comment by nickmoreton** [comment]
While my fixes so far here: https://github.com/longclawshop/longclaw/pull/489 may not help you when installing the package from PyPi the `No module named 'wagtail.core'` error is fixed by updating the imports thats changed around Wagtail v3.0
